---
name: Bimedoc center scrap

env:
  BIMEDOC_API_KEY: ${{ secrets.BIMEDOC_API_KEY }}
on:
  schedule:
    - cron: "0 * * * *"
  # Allow running manually
  workflow_dispatch:

jobs:
  scrape:
    name: "Bimedoc center scrap"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
          token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: make install
      - name: "Bimedoc scrap..."
        run: make bimedocscrap
      - name: "Copy output file"
        run: cp data/output/bimedoc_centers.json .
      - name: "Get folder from data-auto"
        run: |
          git clone --branch data-auto https://github.com/CovidTrackerFr/vitemadose.git tmp/
          cp -R tmp/data/output/* data/output
          rm -rf tmp/
          cp bimedoc_centers.json bimedoc_center_list.json
          cp bimedoc_centers.json bimedoc_center_list.json data/output
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated Bimedoc centers
          push_options: "--force HEAD:data-auto"
